# Generated by Django 5.1 on 2024-08-29 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('year', models.IntegerField(default=0)),
                ('branch', models.CharField(choices=[('Common', 'common/all'), ('CSE.', 'computer science and engg'), ('EC.', 'electronics and comm.'), ('Elec.', 'electrical'), ('IT.', 'information technology'), ('Mech.', 'mechanical'), ('Civil', 'civil'), ('AI.', 'Artificial Intelligence')], default='Common', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year', models.IntegerField(default=0)),
                ('branch', models.CharField(choices=[('Common', 'common/all'), ('CSE.', 'computer science and engg'), ('EC.', 'electronics and comm.'), ('Elec.', 'electrical'), ('IT.', 'information technology'), ('Mech.', 'mechanical'), ('Civil', 'civil'), ('AI.', 'Artificial Intelligence')], default='Common', max_length=30)),
                ('views', models.IntegerField(default=0)),
                ('viewed_by', models.ManyToManyField(blank=True, related_name='viewed_subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('link', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('completed_by', models.ManyToManyField(blank=True, related_name='completed_items', to=settings.AUTH_USER_MODEL)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_items', to=settings.AUTH_USER_MODEL)),
                ('revision_by', models.ManyToManyField(blank=True, related_name='revision_items', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.subject')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(default=None, max_length=255)),
                ('completed_by', models.ManyToManyField(blank=True, related_name='completed_units', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(related_name='units', to='website.item')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='website.subject')),
            ],
        ),
    ]
