# Generated by Django 5.1 on 2024-08-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='codes',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
