# Generated by Django 5.0.6 on 2024-07-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_item_revision_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
