# Generated by Django 5.0.6 on 2024-07-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_subject_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='revision',
            field=models.BooleanField(default=False),
        ),
    ]
