# Generated by Django 5.0.7 on 2024-08-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_subject_viewed_by_subject_views_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(choices=[('Common', 'common/all'), ('CSE.', 'computer science and engg'), ('EC.', 'electronics and comm.'), ('Elec.', 'electrical'), ('IT.', 'information technology'), ('Mech.', 'mechanical'), ('Civil', 'civil'), ('AI.', 'Artificial Intelligence')], default='Common', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
