# Generated by Django 5.0.7 on 2024-08-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_item_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.IntegerField(default=0),
        ),
    ]
