# Generated by Django 5.0.7 on 2024-08-14 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_unit_completed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='completed_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='revision_by',
            field=models.ManyToManyField(blank=True, related_name='revision_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
