# Generated by Django 5.0.7 on 2024-08-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='no_units',
        ),
    ]
