# Generated by Django 5.0.7 on 2024-08-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_subject_no_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='item',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='completed',
        ),
    ]
