# Generated by Django 5.0.7 on 2024-08-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_item_completed_remove_item_revision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
    ]
